### ISSUE TITLE
weight vs word count

### ISSUE THREAD

**Issue by ghostsquad** [mistic100/jQCloud#10]
I was wondering if I should be doing so special math to normalize weights. Given a very small word cloud like this:

```
var words = [
    { text: "blah", weight:  2 },
    { text: "test", weight:  1 },
    { text: "foo", weight:  1 },           
    { text: "bar", weight:  1 },
];
```

The cloud that is generated chooses the absolute largest size for the word with weight: 2 and the absolute smallest size for the words with weight: 1.

If I set "steps: 2" on cloud options, then I get the 2 absolute smallest font sizes.

**Comment by mistic100** [comment]
I cover understand what is your problem

**Comment by ghostsquad** [comment]
I'd like to be able to get the "in-between" font sizes even when there's not in-between weights.

**Comment by mistic100** [comment]
still no clue of what you want

add a complete example, schematics if you want, but here I can't help you

**Comment by rubenheymans** [comment]
you can set a class `{text: "PPE", weight: 10, html: {class: 'weight-10'}},`
and set font-size in css: `#home .cloud .weight-10 {
    font-size: 30px;
    color: #00348F;
}`
