### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by RohanSakhale** [mistic100/jQCloud#13]
Being trying to digg into this with small example but not able to implement the simplest given example too, not sure where might I be going wrong, but need your help in implementing this.

Below is the small snippet of code I am using

```
<div id="cloud">
</div>
<script>
$(function(){
  var words = [
  {text: "Lorem", weight: 13},
  {text: "Ipsum", weight: 10.5},
  {text: "Dolor", weight: 9.4},
  {text: "Sit", weight: 8},
  {text: "Amet", weight: 6.2},
  {text: "Consectetur", weight: 5},
  {text: "Adipiscing", weight: 5}
];

$('#cloud').jQCloud(words);
});
</script>
```

Libraries I am using

1. jQuery - 1.11.3
2. jQuery-UI - 1.11.3
3. Bootstrap - 3.3.5
4. jQCloud2 - 2.0.1

I don't see any code getting generated via jQCloud library, is it something wrong I have been doing. Your help is appreciated

Issue might not be in library but over my usage part.

Seeking help over stackflow as well - http://stackoverflow.com/questions/32804718/jqcloud-not-generating-any-elements

**Comment by mistic100** [comment]
Well you got your answer => width and height.
Which is answered in the doc actually (big red note)
http://mistic100.github.io/jQCloud/index.html#usage
