### ISSUE TITLE
Why it doesn't show all words I specified?

### ISSUE THREAD

**Issue by ermolaevalexey** [mistic100/jQCloud#14]
I have an array of 26 words, but on the screen appears only 8 of them. Is there a property which can manage qauntity of showing words?

**Comment by mistic100** [comment]
It only display words that can fit in the container. You can either enlarge the container or use a smaller font.

**Comment by mistic100** [comment]
Or set `removeOverflowing` to false http://mistic100.github.io/jQCloud/#cloud-options

**Comment by ermolaevalexey** [comment]
Thank you) setting container height helped
