### ISSUE TITLE
All the given words are not shown on cloud..

### ISSUE THREAD

**Issue by vtxmg** [mistic100/jQCloud#23]
I have used this plugins in several website but all the given words are not shown, only some of them are shown... anybody have any idea whats wrong with my code... for reference  you can visit my plugin included website http://www.prastakhabar.com

**Comment by mistic100** [comment]
Please read the doc http://mistic100.github.io/jQCloud/#cloud-options set `removeOverflowing` to true if you want to allow words to be placed outside the container.

And #18
