### ISSUE TITLE
How to add a custom class?

### ISSUE THREAD

**Issue by agungwiseso** [mistic100/jQCloud#25]
Hi, Thanks for creating amazin this plugin.
I wanna ask, How to add a custom class dynamic?
Example:
`<span id="demo-update_word_0" class="w10 mycustomclass mylorem" style="position: absolute; left: 147.5px; top: 94px;">myLorem</span>`

Thanks

**Comment by mistic100** [comment]
Did you read the doc ? http://mistic100.github.io/jQCloud/#words-options `html` property
