### ISSUE TITLE
Not every word is shown on the window.

### ISSUE THREAD

**Issue by mj-fintech** [mistic100/jQCloud#29]
Hello I am getting to know this jQCloud now. 

I have an issue:

I have 66 words in the words variable. It seems like every words are visualized on the full-web in my laptop, but in my phone, only 20-ish words are shown. Why is that? Is there any solution to this problem?
I want to see every words that I have in the var list. Below is my code

[<script type="text/javascript">
						
						var words = [
							{text: "Lorem", weight: 13},
							{text: "Ipsum", weight: 10.5},
							{text: "Dolor", weight: 9.4},
							{text: "Sit", weight: 8},
							{text: "Amet", weight: 6.2},
							{text: "Consectetur", weight: 5},
							{text: "Adipiscing", weight: 5},
							{text: "Elit", weight: 5},
							{text: "Nam et", weight: 5},
							{text: "Leo", weight: 4},
							{text: "Sapien", weight: 4},
							{text: "Pellentesque", weight: 3},
							{text: "habitant", weight: 3},
							{text: "morbi", weight: 3},
							{text: "tristisque", weight: 3},
							{text: "senectus", weight: 3},
							{text: "et netus", weight: 3},
							{text: "et malesuada", weight: 3},
							{text: "fames", weight: 2},
							{text: "ac turpis", weight: 2},
							{text: "egestas", weight: 2},
							{text: "Aenean", weight: 2},
							{text: "vestibulum", weight: 2},
							{text: "elit", weight: 2},
							{text: "sit amet", weight: 2},
							{text: "metus", weight: 2},
							{text: "adipiscing", weight: 2},
							{text: "ut ultrices", weight: 2},
							{text: "justo", weight: 1},
							{text: "dictum", weight: 1},
							{text: "Adipiscing", weight: 5},
							{text: "El3t", weight: 5},
							{text: "Na4 et", weight: 5},
							{text: "Le2", weight: 4},
							{text: "Sa2ien", weight: 4},
							{text: "Pe2lentesque", weight: 3},
							{text: "ha2itant", weight: 3},
							{text: "mo2bi", weight: 3},
							{text: "tr2stisque", weight: 3},
							{text: "se2ectus", weight: 3},
							{text: "et2netus", weight: 3},
							{text: "et2malesuada", weight: 3},
							{text: "fa2es", weight: 2},
							{text: "ac2turpis", weight: 2},
							{text: "eg2stas", weight: 2},
							{text: "Ae2ean", weight: 2},
							{text: "ve2tibulum", weight: 2},
							{text: "el2t", weight: 2},
							{text: "si2 amet", weight: 2},
							{text: "me2us", weight: 2},
							{text: "ad2piscing", weight: 2},
							{text: "ut2ultrices", weight: 2},
							{text: "ju2to", weight: 1},
							{text: "di2tum", weight: 1},
							{text: "Ut et leo", weight: 1},
							{text: "metus", weight: 1},
							{text: "at molestie", weight: 1},
							{text: "purus", weight: 1},
							{text: "Curabitur", weight: 1},
							{text: "diam", weight: 1},
							{text: "dui", weight: 1},
							{text: "ullamcorper", weight: 1},
							{text: "id vuluptate ut", weight: 1},
							{text: "mattis", weight: 1},
							{text: "et nulla", weight: 1},
							{text: "Sed", weight: 1}
						];

	                    $('#demo').jQCloud(words, {

	                    		autoResize: true                    		

	                    });

					</script>]

I tried not to put the autoResize, but it doesn't solve the problem.
Please let me know how should I do this. For the div size, I put 80% as the div width, and I didn't put any constraint for the height. Let me know when you got some solutions for this please. 

Thank you!

**Comment by mistic100** [comment]
Words are added to the container until there is no place left, if not every word can fit in the available space then some will not be rendered. That's exactly how it was intended to work.

You can increase the size of your container or set `removeOverflowing` to `false` (in which case words might overlap the rest of the page.

As explained in #11 and #18 I will not modify the algorithm. But contributions are welcomed.
